version: "3"
services:
  db:
    image: mysql:5.7
    command: mysqld --user=root --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./demo/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: addresslist
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql
      LANG: C.UTF-8
  adminer:
    image: adminer
    restart: always
    ports:
      - 10086:8080